import { useEffect, useState } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Legend, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Activity, BarChart3, Droplets, Truck } from 'lucide-react';
import { api } from '../utils/api.js';
import { analyticsSeries } from '../data/mockData.js';
import { StatCard, StatusBadge } from '../components/Cards.jsx';

export default function Analytics() {
  const [series, setSeries] = useState(analyticsSeries);
  const [totals, setTotals] = useState({ totalWaterAllocated: 29400, totalWaterDelivered: 26800, tankersDispatched: 154, areasServed: 3, activeTankers: 3, openComplaints: 8 });
  const [forecasts, setForecasts] = useState([]);
  useEffect(() => { api.get('/analytics').then((r) => { setTotals(r.data.totals); setSeries(r.data.series.map((x) => ({ day: new Date(x.date).toLocaleDateString(), delivered: x.waterDeliveredKL, allocated: x.waterAllocatedKL, complaints: x.complaintsReceived, efficiency: x.supplyEfficiencyPercent, tankers: x.tankersDispatched }))); }).catch(() => {}); api.get('/ai/forecast').then((r) => setForecasts(r.data)).catch(() => setForecasts([{ area: { name: 'Ward 33 - Laxmi Nagar' }, demandForecastKL: 930, shortageProbability: 0.72, risk: 'high' }])); }, []);
  return <div className="space-y-6"><h1 className="flex items-center gap-3 text-4xl font-black"><BarChart3 className="text-jal-600" /> Transparency & Analytics</h1><div className="grid gap-4 md:grid-cols-3"><StatCard title="Water allocated" value={`${totals.totalWaterAllocated} KL`} icon={Droplets} /><StatCard title="Water delivered" value={`${totals.totalWaterDelivered} KL`} icon={Activity} /><StatCard title="Tankers dispatched" value={totals.tankersDispatched} icon={Truck} /></div><div className="grid gap-6 lg:grid-cols-2"><div className="glass-card p-5"><h2 className="mb-4 text-xl font-black">Consumption trends</h2><ResponsiveContainer width="100%" height={300}><AreaChart data={series}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="day" /><YAxis /><Tooltip /><Legend /><Area dataKey="allocated" fill="#bae6fd" stroke="#0284c7" /><Area dataKey="delivered" fill="#bbf7d0" stroke="#16a34a" /></AreaChart></ResponsiveContainer></div><div className="glass-card p-5"><h2 className="mb-4 text-xl font-black">Complaint and tanker trends</h2><ResponsiveContainer width="100%" height={300}><BarChart data={series}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="day" /><YAxis /><Tooltip /><Legend /><Bar dataKey="complaints" fill="#f59e0b" /><Bar dataKey="tankers" fill="#0ea5e9" /></BarChart></ResponsiveContainer></div></div><div className="glass-card p-5"><h2 className="mb-4 text-xl font-black">AI shortage prediction</h2><div className="grid gap-3 md:grid-cols-3">{forecasts.map((f, i) => <div key={i} className="rounded-2xl bg-sky-50 p-4 dark:bg-slate-800"><StatusBadge status={f.risk} /><h3 className="mt-2 font-black">{f.area.name}</h3><p>Forecast: {f.demandForecastKL} KL</p><p>Shortage probability: {Math.round(f.shortageProbability * 100)}%</p></div>)}</div></div></div>;
}
